def personal_sum(numbers):
    
    result = 0
    incorrect_data = 0

    for i in numbers:

        try:

            result += i

        except TypeError:

            incorrect_data += 1
            print(f'Некорректный тип данных для подсчёта суммы - {i}')

    return (result, incorrect_data)

def calculate_average(numbers):

    try:

        per_sum = personal_sum(numbers)

        avg = per_sum[0] / (len(numbers) - per_sum[1])

        return avg

    except ZeroDivisionError:
        return 0

    except TypeError:
        print('В numbers записан некорректный тип данных')
        return None
# print(calculate_average(1, 2, 3, 'w', 4, 'n'))
print(f'Результат 1: {calculate_average("1, 2, 3")}')
print(f'Результат 2: {calculate_average([1, "Строка", 3, "Ещё Строка"])}')
print(f'Результат 3: {calculate_average(567)}')
print(f'Результат 4: {calculate_average([42, 15, 36, 13])}')
